# Welcome to Jekyll!
#

#------------------Site Settings------------------
title: Tyrone Anthony
description: |
  Photographer<br>
  Documenting timeframes
owner: Tyrone Ong # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: ongtypc@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: /:categories/:title/

#------------------Index Content------------------
#'banner'
mainbutton: Portfolio
mainbuttonlink: portfolio
scrollbutton: Learn More

#Wrapper 'one'
header: |
  Freelance event photographer<br>based in Malaysia
subheader: |
  I shoot weddings, graduations, and all other sorts of events. 

#Wrapper 'two'
spotlight1: |
  The timeframes
spotlight1para: |
  I believe in a life of timeframes. I believe things change, and people come and go; different timeframes, different places, different people. <br><br>
  I also believe in making records. I believe that one should not feel regretful for having no record of the important moments. 
spotlight1img: assets/img/site/spotlight01.jpg
spotlight2: |
  The documentary approach
spotlight2para: |
  For making a record, I strive for genuine moments. <br><br>
  Enter the documentary approach. I strive to capture the true reflection and emotions of an event. I believe a good photograph captures the souls. 
spotlight2img: assets/img/site/spotlight02.jpg
spotlight3: |
  Timeless photographs
spotlight3para: |
  A classic photo album is like a music mixtape - something that is created to be enjoyed for decades and on. I also strive to capture classic looking photographs, something that we would still enjoy when we grow old, perhaps for your grandchildren too. <br><br>
  It's true, the classics never get old. 
spotlight3img: assets/img/site/spotlight03.jpg

#Wrapper 'three'


#Wrapper 'cta'
cta-header: |
  Learn more
cta-para: |
  More questions? No problem. Call me or text me. 
cta-button: Contact Me
cta-buttonlink: about#contact
cta-button2: Portfolio
cta-button2link: portfolio

#------------------Page Content------------------
#Portfolio
pspotlight1: |
  Marriage
pspotlight1para: |
  Morbi mattis mi consectetur tortor elementum, varius pellentesque velit convallis. <br><br>
  Aenean tincidunt lectus auctor mauris maximus, ac scelerisque ipsum tempor. Duis vulputate ex et ex tincidunt, quis lacinia velit aliquet. Duis non efficitur nisi, id malesuada justo. Maecenas sagittis felis ac sagittis semper. 
pspotlight1img: ../assets/img/site/spotlight01.jpg
pspotlight2: |
  Graduations
pspotlight2para: |
  Morbi mattis mi consectetur tortor elementum, varius pellentesque velit convallis. <br><br>
  Aenean tincidunt lectus auctor mauris maximus, ac scelerisque ipsum tempor. Duis vulputate ex et ex tincidunt, quis lacinia velit aliquet. Duis non efficitur nisi, id malesuada justo. Maecenas sagittis felis ac sagittis semper. 
pspotlight2img: ../assets/img/site/spotlight02.jpg
pspotlight3: |
  Events
pspotlight3para: |
  Morbi mattis mi consectetur tortor elementum, varius pellentesque velit convallis. <br><br>
  Aenean tincidunt lectus auctor mauris maximus, ac scelerisque ipsum tempor. Duis vulputate ex et ex tincidunt, quis lacinia velit aliquet. Duis non efficitur nisi, id malesuada justo. Maecenas sagittis felis ac sagittis semper. 
pspotlight3img: ../assets/img/site/spotlight03.jpg



#------------------Others------------------

social:
  #twitter: https://twitter.com/tyrone0ng
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/tyroneanthonyphoto/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/tyrone0ng/
  #youtube-square:
  spotify: https://open.spotify.com/user/1277814824
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed