# Welcome to Jekyll!
#

#------------------Site Settings------------------
title: by.tyroneong
subtitle: |
  Photographer<br>
  Documenting timeframes
description: Lifestyle photographer based in Malaysia.
owner: Tyrone Ong # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: ongtypc@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyrng.github.io" # the base hostname & protocol for your site
permalink: /:categories/:title/
default_bg: sitelogo.png
avatar: images/site/me1.jpg

#------------------Index Content------------------
#'banner'
mainbutton: Portfolio
mainbuttonlink: portfolio
scrollbutton: Learn More

#Wrapper 'one'
header: |
  Lifestyle photographer<br>based in Malaysia
subheader: |
  I shoot weddings, graduations, and all other sorts of events.
#subheader2: |
#  Meanwhile, I shoot other genres of photography as a hobby.<br>I also write and curate music.
icon1link: portfolio/
icon1label: Photographing
#icon2link: blog/
icon2label: Blogging
icon3link: https://open.spotify.com/user/1277814824
icon3label: Music Curating

#Wrapper 'two'
spotlight1: |
  The timeframes
spotlight1para: |
  I believe in a life of timeframes. I believe things change, and people come and go; different timeframes, different places, different people. <br><br>
  I also believe in making records. I believe that one should not feel regretful for having no record of the important moments.
spotlight1img: images/site/spotlight01.jpg
spotlight2: |
  The documentary approach
spotlight2para: |
  For making a record, I strive for genuine moments. <br><br>
  Enter the documentary approach. I strive to capture the true reflection and emotions of an event. I believe a good photograph captures the souls.
spotlight2img: images/site/spotlight02.jpg
spotlight3: |
  Timeless photographs
spotlight3para: |
  A classic photo album is like a music mixtape - something that is created to be enjoyed for decades and on. I also strive to capture classic looking photographs, something that we would still enjoy when we grow old, perhaps for your grandchildren too. <br><br>
  It's true, the classics never get old.
spotlight3img: images/site/spotlight03.jpg

#Wrapper 'three'


#Wrapper 'cta'
cta-header: |
  Learn more
cta-para: |
  More questions? No problem. Just write me a message!
cta-button: Contact Me
cta-buttonlink: about#contact
cta-button2: Portfolio
cta-button2link: portfolio

#------------------Page Content------------------
#Portfolio
pspotlight1: |
  Marriage
pspotlight1para: |
  Of all the timeframes in our lives, marriage is of upmost important. <br><br>I crave to capture genuine emotions, because I believe a moment that is interfered by the photographer isn’t a genuine moment — it is the photographer’s idea of what that moment should be. <br><br><b>Services offered: Registration of Marriage, Wedding Actual Day, Wedding Dinner. </b>
pspotlight1img: ../images/portfolio/posts/marriage/wedding-janeshaun/wedding-janeshaun 022.jpg
pspotlight2: |
  Graduations
pspotlight2para: |
  Moment of a lifetime. Gowns and mortarboards, a vision of hope. <br><br><b>Services offered: Personal/Group Portraits, Convocation Event Photography.</b>
pspotlight2img: ../images/portfolio/posts/graduations/graduation-victor/graduation-victor 007.jpg
pspotlight3: |
  Events
pspotlight3para: |
  From birthday parties to corporate events, or... you name it. <br><br><b>Services offered: Parties, sport events, concerts, fashion walks, corporate events, etc. </b>
pspotlight3img: ../images/portfolio/posts/events/event-annualcamp/event-annualcamp 001.jpg

#About Me
aboutpic01: ../images/site/me1.jpg
aboutpara01: |
  Born under the warm sunshine of the East Coast, the (once) kiddo Tyrone was mesmerized by two things - the soothing tropical (and rather salty) breeze as it gracefully sang and touched his face, and a machine capable of capturing lights and moments, which his father gave him as a gift when he was 10 years old. The teeny (current) Tyrone lives and studies among tall concretes in Kuala Lumpur to achieve his ambition as a Software Engineer - the boring (future) Tyrone.
aboutpic02: ../images/site/me2.jpg
aboutpara02: |
  Obsessed with the cinematic style, Tyrone finds ways to fuse the style to many genres, primirily street, portrait, and lifestyle photography. In late 2015, he read about a photography article about the 'quiet in-between moments' - which had driven him even more obsessive. Mid 2016, he then discovered the 'documentary approach' in wedding photography. It is also that time he decided to start his freelance career by incorporating all his findings and 10 years of experience in photography.

#------------------Content in Personal------------------
#personalwords: |
#  Aww how awkward! This page is techinically ready, but the photos are not! Curating... <br><br><br>
#------------------Others------------------

sayat: https://sayat.me/tyrone0ng/
social:
  #twitter: https://twitter.com/tyrone0ng
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/tyronephoto/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/by.tyrone0ng/
  #youtube-square:
  #spotify: https://open.spotify.com/user/1277814824
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

google-analytics: |
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67534177-2', 'auto');
  ga('send', 'pageview');

plugins:
  - jekyll-seo-tag
  - "jekyll/figure"

# Build settings
markdown: kramdown
#sass:
#  style: compressed


#-----------------SEO-----
#author: tyrone0ng
twitter:
  username: tyrone0ng

facebook:
 app_id: 1483358635064207
 publisher: https://www.facebook.com/tyroneanthonyphoto
 admins: ongtypc

 logo: favicon.png
